version: "3.9" 

services:
#nestjs backend
  backend:
    env_file:
      - ./backend/.env
  # build from Dockerfile
    build:
      dockerfile: ./backend/Dockerfile
      #simply the backend folder chat
      context: ./
      # only build the dev stage from Dockerfile
      target: dev
    command: npm run start:dev
    depends_on: 
      - postgres
    environment:
      NODE_ENV: dev
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229
  postgres:
    env_file:
      - ./backend/.env
    #use postgres image from dockerhub
    image: postgres:14.4
    ports:
      - 5432:5432

  postgres_admin:
    env_file:
      - ./backend/.env
    image: dpage/pgadmin4:6.11
    depends_on: 
      - postgres
    ports:
      - 5050:80
    